import {useCallback,useEffect,useState} from 'react';
import './visitor-integration.css';
type Visitor={visitor_id:string;first_name:string;last_name:string;status:string;stage:string;home_cell_id:string|null;home_cell_name:string|null;discipleship_started:boolean;discipleship_completed:boolean;next_follow_up_date:string|null;integration_notes:string};
type Cell={id:string;name:string};
const stages=[['NEW','New Visitor'],['FOLLOW_UP','Follow-up'],['CONNECTED','Connected'],['DISCIPLESHIP','Discipleship'],['MEMBERSHIP','Membership']];
export default function VisitorIntegration({apiBaseUrl,authFetch}:{apiBaseUrl:string;authFetch:(url:string,options?:RequestInit)=>Promise<Response>}){
 const [visitors,setVisitors]=useState<Visitor[]>([]),[cells,setCells]=useState<Cell[]>([]);
 const [draft,setDraft]=useState<Visitor|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const r=await authFetch(apiBaseUrl+'/visitor-integration');if(!r.ok)throw Error('Unable to load visitor integration');const data=await r.json();setVisitors(data.visitors||[]);setCells(data.homeCells||[]);}catch(e){setMessage(e instanceof Error?e.message:'Load failed');}},[apiBaseUrl,authFetch]);
 useEffect(()=>{void load();},[load]);
 async function save(){if(!draft)return;setBusy(true);setMessage('');try{const r=await authFetch(apiBaseUrl+'/visitor-integration/'+draft.visitor_id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({stage:draft.stage,homeCellId:draft.home_cell_id||undefined,discipleshipStarted:draft.discipleship_started,discipleshipCompleted:draft.discipleship_completed,nextFollowUpDate:draft.next_follow_up_date?.slice(0,10)||undefined,integrationNotes:draft.integration_notes})});if(!r.ok){const e=await r.json().catch(()=>({}));throw Error(Array.isArray(e.message)?e.message.join(', '):e.message||'Save failed');}setDraft(null);await load();setMessage('Visitor integration saved.');}catch(e){setMessage(e instanceof Error?e.message:'Save failed');}finally{setBusy(false);}}
 const due=visitors.filter(v=>v.stage!=='MEMBERSHIP'&&v.next_follow_up_date&&v.next_follow_up_date.slice(0,10)<=new Date().toISOString().slice(0,10)).length;
 return <section className="clgf-visitor-integration"><h3>Visitor Integration Tracking</h3><p>Home Cells, discipleship and membership journey.</p>
 <div className="clgf-integration-stats">{[['Active Journeys',visitors.filter(v=>v.stage!=='MEMBERSHIP').length],['Discipleship',visitors.filter(v=>v.stage==='DISCIPLESHIP').length],['Membership',visitors.filter(v=>v.stage==='MEMBERSHIP').length],['Follow-ups Due',due]].map(([name,n])=><div key={name}><strong>{n}</strong><span>{name}</span></div>)}</div>
 <div className="clgf-integration-list">{visitors.map(v=><article className="clgf-integration-card" key={v.visitor_id}><h4>{v.first_name} {v.last_name}</h4><p><b>Stage:</b> {stages.find(s=>s[0]===v.stage)?.[1]||v.stage}</p><p><b>Home Cell:</b> {v.home_cell_name||'Not connected'}</p><p><b>Discipleship:</b> {v.discipleship_completed?'Completed':v.discipleship_started?'In progress':'Not started'}</p><button type="button" onClick={()=>setDraft({...v})}>Update Integration</button>
 {draft?.visitor_id===v.visitor_id&&<div className="clgf-integration-editor"><label>Integration Stage<select value={draft.stage} disabled={v.status==='CONVERTED'} onChange={e=>setDraft({...draft,stage:e.target.value})}>{stages.filter(s=>s[0]!=='MEMBERSHIP'||v.status==='CONVERTED').map(s=><option value={s[0]} key={s[0]}>{s[1]}</option>)}</select></label>
 <label>Home Cell<select value={draft.home_cell_id||''} onChange={e=>setDraft({...draft,home_cell_id:e.target.value||null})}><option value="">Not assigned</option>{cells.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>
 <label><input type="checkbox" checked={draft.discipleship_started} onChange={e=>setDraft({...draft,discipleship_started:e.target.checked,discipleship_completed:e.target.checked?draft.discipleship_completed:false})}/> Discipleship Started</label>
 <label><input type="checkbox" checked={draft.discipleship_completed} onChange={e=>setDraft({...draft,discipleship_completed:e.target.checked,discipleship_started:e.target.checked?true:draft.discipleship_started})}/> Discipleship Completed</label>
 <label>Next Follow-up Date<input type="date" value={draft.next_follow_up_date?.slice(0,10)||''} onChange={e=>setDraft({...draft,next_follow_up_date:e.target.value||null})}/></label>
 <label>Notes<textarea rows={3} value={draft.integration_notes} onChange={e=>setDraft({...draft,integration_notes:e.target.value})}/></label>
 <button type="button" disabled={busy} onClick={()=>void save()}>Save Integration</button><button type="button" onClick={()=>setDraft(null)}>Cancel</button></div>}</article>)}{!visitors.length&&<p>No active visitors recorded.</p>}</div>{message&&<p role="status">{message}</p>}</section>;
}
